[buildpack]
name = "Ruby"
ruby_version = "2.5.7"

  [publish.Ignore]
  files = [
    "spec/"
  ]

  [[publish.Vendor]]
  # get tokens for logging build tokens
  url = "https://codon-buildpacks.s3.amazonaws.com/buildpacks/heroku/ruby.tgz"
  dir = "."
  files = ["./.env"]
  [[publish.Vendor]]
  url = "https://heroku-buildpack-ruby.s3.us-east-1.amazonaws.com/cedar-14/ruby-2.5.7.tgz"
  dir = "vendor/ruby/cedar-14"
  [[publish.Vendor]]
  url = "https://heroku-buildpack-ruby.s3.us-east-1.amazonaws.com/heroku-16/ruby-2.5.7.tgz"
  dir = "vendor/ruby/heroku-16"
  [[publish.Vendor]]
  url = "https://heroku-buildpack-ruby.s3.us-east-1.amazonaws.comy/heroku-18/ruby-2.5.7.tgz"
  dir = "vendor/ruby/heroku-18"
